export const ErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_JSON: "INVALID_JSON",
  MISSING_FIELD: "MISSING_FIELD",
  INVALID_FORMAT: "INVALID_FORMAT",

  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  GONE: "GONE",

  DB_ERROR: "DB_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  DEPRECATED_ENDPOINT: "DEPRECATED_ENDPOINT",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const HTTP_STATUS: Record<ErrorCode, number> = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  VALIDATION_ERROR: 400,
  INVALID_JSON: 400,
  MISSING_FIELD: 400,
  INVALID_FORMAT: 400,
  NOT_FOUND: 404,
  ALREADY_EXISTS: 409,
  GONE: 410,
  DB_ERROR: 500,
  INTERNAL_ERROR: 500,
  DEPRECATED_ENDPOINT: 410,
};
